apiVersion: "experimental.mattmoor.io/v1alpha1"
kind: Build
metadata:
  name: example-build
spec:
  source:
    repoSource:
      repoName: default
      branchName: master
  steps:
  - name: gcr.io/cloud-builders/gcloud:latest
    entrypoint: /bin/cat
    args: [/workspace/.gitignore]
