// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	experimental "github.com/mattmoor/hello-apiserver/pkg/apis/experimental"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Build_To_experimental_Build,
		Convert_experimental_Build_To_v1alpha1_Build,
		Convert_v1alpha1_BuildList_To_experimental_BuildList,
		Convert_experimental_BuildList_To_v1alpha1_BuildList,
		Convert_v1alpha1_BuildSpec_To_experimental_BuildSpec,
		Convert_experimental_BuildSpec_To_v1alpha1_BuildSpec,
		Convert_v1alpha1_BuildStatus_To_experimental_BuildStatus,
		Convert_experimental_BuildStatus_To_v1alpha1_BuildStatus,
		Convert_v1alpha1_BuildStatusStrategy_To_experimental_BuildStatusStrategy,
		Convert_experimental_BuildStatusStrategy_To_v1alpha1_BuildStatusStrategy,
		Convert_v1alpha1_BuildStrategy_To_experimental_BuildStrategy,
		Convert_experimental_BuildStrategy_To_v1alpha1_BuildStrategy,
		Convert_v1alpha1_RepoSourceSpec_To_experimental_RepoSourceSpec,
		Convert_experimental_RepoSourceSpec_To_v1alpha1_RepoSourceSpec,
		Convert_v1alpha1_SourceSpec_To_experimental_SourceSpec,
		Convert_experimental_SourceSpec_To_v1alpha1_SourceSpec,
		Convert_v1alpha1_StepSpec_To_experimental_StepSpec,
		Convert_experimental_StepSpec_To_v1alpha1_StepSpec,
		Convert_v1alpha1_StorageSourceSpec_To_experimental_StorageSourceSpec,
		Convert_experimental_StorageSourceSpec_To_v1alpha1_StorageSourceSpec,
		Convert_v1alpha1_VolumeSpec_To_experimental_VolumeSpec,
		Convert_experimental_VolumeSpec_To_v1alpha1_VolumeSpec,
	)
}

func autoConvert_v1alpha1_Build_To_experimental_Build(in *Build, out *experimental.Build, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BuildSpec_To_experimental_BuildSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BuildStatus_To_experimental_BuildStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Build_To_experimental_Build is an autogenerated conversion function.
func Convert_v1alpha1_Build_To_experimental_Build(in *Build, out *experimental.Build, s conversion.Scope) error {
	return autoConvert_v1alpha1_Build_To_experimental_Build(in, out, s)
}

func autoConvert_experimental_Build_To_v1alpha1_Build(in *experimental.Build, out *Build, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_experimental_BuildSpec_To_v1alpha1_BuildSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_experimental_BuildStatus_To_v1alpha1_BuildStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_experimental_Build_To_v1alpha1_Build is an autogenerated conversion function.
func Convert_experimental_Build_To_v1alpha1_Build(in *experimental.Build, out *Build, s conversion.Scope) error {
	return autoConvert_experimental_Build_To_v1alpha1_Build(in, out, s)
}

func autoConvert_v1alpha1_BuildList_To_experimental_BuildList(in *BuildList, out *experimental.BuildList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]experimental.Build)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BuildList_To_experimental_BuildList is an autogenerated conversion function.
func Convert_v1alpha1_BuildList_To_experimental_BuildList(in *BuildList, out *experimental.BuildList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BuildList_To_experimental_BuildList(in, out, s)
}

func autoConvert_experimental_BuildList_To_v1alpha1_BuildList(in *experimental.BuildList, out *BuildList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]Build, 0)
	} else {
		out.Items = *(*[]Build)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_experimental_BuildList_To_v1alpha1_BuildList is an autogenerated conversion function.
func Convert_experimental_BuildList_To_v1alpha1_BuildList(in *experimental.BuildList, out *BuildList, s conversion.Scope) error {
	return autoConvert_experimental_BuildList_To_v1alpha1_BuildList(in, out, s)
}

func autoConvert_v1alpha1_BuildSpec_To_experimental_BuildSpec(in *BuildSpec, out *experimental.BuildSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_SourceSpec_To_experimental_SourceSpec(&in.Source, &out.Source, s); err != nil {
		return err
	}
	out.Steps = *(*[]experimental.StepSpec)(unsafe.Pointer(&in.Steps))
	out.Images = *(*[]string)(unsafe.Pointer(&in.Images))
	return nil
}

// Convert_v1alpha1_BuildSpec_To_experimental_BuildSpec is an autogenerated conversion function.
func Convert_v1alpha1_BuildSpec_To_experimental_BuildSpec(in *BuildSpec, out *experimental.BuildSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BuildSpec_To_experimental_BuildSpec(in, out, s)
}

func autoConvert_experimental_BuildSpec_To_v1alpha1_BuildSpec(in *experimental.BuildSpec, out *BuildSpec, s conversion.Scope) error {
	if err := Convert_experimental_SourceSpec_To_v1alpha1_SourceSpec(&in.Source, &out.Source, s); err != nil {
		return err
	}
	out.Steps = *(*[]StepSpec)(unsafe.Pointer(&in.Steps))
	out.Images = *(*[]string)(unsafe.Pointer(&in.Images))
	return nil
}

// Convert_experimental_BuildSpec_To_v1alpha1_BuildSpec is an autogenerated conversion function.
func Convert_experimental_BuildSpec_To_v1alpha1_BuildSpec(in *experimental.BuildSpec, out *BuildSpec, s conversion.Scope) error {
	return autoConvert_experimental_BuildSpec_To_v1alpha1_BuildSpec(in, out, s)
}

func autoConvert_v1alpha1_BuildStatus_To_experimental_BuildStatus(in *BuildStatus, out *experimental.BuildStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_BuildStatus_To_experimental_BuildStatus is an autogenerated conversion function.
func Convert_v1alpha1_BuildStatus_To_experimental_BuildStatus(in *BuildStatus, out *experimental.BuildStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_BuildStatus_To_experimental_BuildStatus(in, out, s)
}

func autoConvert_experimental_BuildStatus_To_v1alpha1_BuildStatus(in *experimental.BuildStatus, out *BuildStatus, s conversion.Scope) error {
	return nil
}

// Convert_experimental_BuildStatus_To_v1alpha1_BuildStatus is an autogenerated conversion function.
func Convert_experimental_BuildStatus_To_v1alpha1_BuildStatus(in *experimental.BuildStatus, out *BuildStatus, s conversion.Scope) error {
	return autoConvert_experimental_BuildStatus_To_v1alpha1_BuildStatus(in, out, s)
}

func autoConvert_v1alpha1_BuildStatusStrategy_To_experimental_BuildStatusStrategy(in *BuildStatusStrategy, out *experimental.BuildStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_BuildStatusStrategy_To_experimental_BuildStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_BuildStatusStrategy_To_experimental_BuildStatusStrategy(in *BuildStatusStrategy, out *experimental.BuildStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_BuildStatusStrategy_To_experimental_BuildStatusStrategy(in, out, s)
}

func autoConvert_experimental_BuildStatusStrategy_To_v1alpha1_BuildStatusStrategy(in *experimental.BuildStatusStrategy, out *BuildStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_experimental_BuildStatusStrategy_To_v1alpha1_BuildStatusStrategy is an autogenerated conversion function.
func Convert_experimental_BuildStatusStrategy_To_v1alpha1_BuildStatusStrategy(in *experimental.BuildStatusStrategy, out *BuildStatusStrategy, s conversion.Scope) error {
	return autoConvert_experimental_BuildStatusStrategy_To_v1alpha1_BuildStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_BuildStrategy_To_experimental_BuildStrategy(in *BuildStrategy, out *experimental.BuildStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_BuildStrategy_To_experimental_BuildStrategy is an autogenerated conversion function.
func Convert_v1alpha1_BuildStrategy_To_experimental_BuildStrategy(in *BuildStrategy, out *experimental.BuildStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_BuildStrategy_To_experimental_BuildStrategy(in, out, s)
}

func autoConvert_experimental_BuildStrategy_To_v1alpha1_BuildStrategy(in *experimental.BuildStrategy, out *BuildStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_experimental_BuildStrategy_To_v1alpha1_BuildStrategy is an autogenerated conversion function.
func Convert_experimental_BuildStrategy_To_v1alpha1_BuildStrategy(in *experimental.BuildStrategy, out *BuildStrategy, s conversion.Scope) error {
	return autoConvert_experimental_BuildStrategy_To_v1alpha1_BuildStrategy(in, out, s)
}

func autoConvert_v1alpha1_RepoSourceSpec_To_experimental_RepoSourceSpec(in *RepoSourceSpec, out *experimental.RepoSourceSpec, s conversion.Scope) error {
	out.ProjectId = in.ProjectId
	out.RepoName = in.RepoName
	out.BranchName = in.BranchName
	out.TagName = in.TagName
	out.CommitSHA = in.CommitSHA
	out.Dir = in.Dir
	return nil
}

// Convert_v1alpha1_RepoSourceSpec_To_experimental_RepoSourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_RepoSourceSpec_To_experimental_RepoSourceSpec(in *RepoSourceSpec, out *experimental.RepoSourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RepoSourceSpec_To_experimental_RepoSourceSpec(in, out, s)
}

func autoConvert_experimental_RepoSourceSpec_To_v1alpha1_RepoSourceSpec(in *experimental.RepoSourceSpec, out *RepoSourceSpec, s conversion.Scope) error {
	out.ProjectId = in.ProjectId
	out.RepoName = in.RepoName
	out.BranchName = in.BranchName
	out.TagName = in.TagName
	out.CommitSHA = in.CommitSHA
	out.Dir = in.Dir
	return nil
}

// Convert_experimental_RepoSourceSpec_To_v1alpha1_RepoSourceSpec is an autogenerated conversion function.
func Convert_experimental_RepoSourceSpec_To_v1alpha1_RepoSourceSpec(in *experimental.RepoSourceSpec, out *RepoSourceSpec, s conversion.Scope) error {
	return autoConvert_experimental_RepoSourceSpec_To_v1alpha1_RepoSourceSpec(in, out, s)
}

func autoConvert_v1alpha1_SourceSpec_To_experimental_SourceSpec(in *SourceSpec, out *experimental.SourceSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_StorageSourceSpec_To_experimental_StorageSourceSpec(&in.StorageSource, &out.StorageSource, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RepoSourceSpec_To_experimental_RepoSourceSpec(&in.RepoSource, &out.RepoSource, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_SourceSpec_To_experimental_SourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_SourceSpec_To_experimental_SourceSpec(in *SourceSpec, out *experimental.SourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_SourceSpec_To_experimental_SourceSpec(in, out, s)
}

func autoConvert_experimental_SourceSpec_To_v1alpha1_SourceSpec(in *experimental.SourceSpec, out *SourceSpec, s conversion.Scope) error {
	if err := Convert_experimental_StorageSourceSpec_To_v1alpha1_StorageSourceSpec(&in.StorageSource, &out.StorageSource, s); err != nil {
		return err
	}
	if err := Convert_experimental_RepoSourceSpec_To_v1alpha1_RepoSourceSpec(&in.RepoSource, &out.RepoSource, s); err != nil {
		return err
	}
	return nil
}

// Convert_experimental_SourceSpec_To_v1alpha1_SourceSpec is an autogenerated conversion function.
func Convert_experimental_SourceSpec_To_v1alpha1_SourceSpec(in *experimental.SourceSpec, out *SourceSpec, s conversion.Scope) error {
	return autoConvert_experimental_SourceSpec_To_v1alpha1_SourceSpec(in, out, s)
}

func autoConvert_v1alpha1_StepSpec_To_experimental_StepSpec(in *StepSpec, out *experimental.StepSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Env = *(*[]string)(unsafe.Pointer(&in.Env))
	out.Dir = in.Dir
	out.Entrypoint = in.Entrypoint
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.Volumes = *(*[]experimental.VolumeSpec)(unsafe.Pointer(&in.Volumes))
	return nil
}

// Convert_v1alpha1_StepSpec_To_experimental_StepSpec is an autogenerated conversion function.
func Convert_v1alpha1_StepSpec_To_experimental_StepSpec(in *StepSpec, out *experimental.StepSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_StepSpec_To_experimental_StepSpec(in, out, s)
}

func autoConvert_experimental_StepSpec_To_v1alpha1_StepSpec(in *experimental.StepSpec, out *StepSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Env = *(*[]string)(unsafe.Pointer(&in.Env))
	out.Dir = in.Dir
	out.Entrypoint = in.Entrypoint
	out.Args = *(*[]string)(unsafe.Pointer(&in.Args))
	out.Volumes = *(*[]VolumeSpec)(unsafe.Pointer(&in.Volumes))
	return nil
}

// Convert_experimental_StepSpec_To_v1alpha1_StepSpec is an autogenerated conversion function.
func Convert_experimental_StepSpec_To_v1alpha1_StepSpec(in *experimental.StepSpec, out *StepSpec, s conversion.Scope) error {
	return autoConvert_experimental_StepSpec_To_v1alpha1_StepSpec(in, out, s)
}

func autoConvert_v1alpha1_StorageSourceSpec_To_experimental_StorageSourceSpec(in *StorageSourceSpec, out *experimental.StorageSourceSpec, s conversion.Scope) error {
	out.Bucket = in.Bucket
	out.Object = in.Object
	out.Generation = in.Generation
	return nil
}

// Convert_v1alpha1_StorageSourceSpec_To_experimental_StorageSourceSpec is an autogenerated conversion function.
func Convert_v1alpha1_StorageSourceSpec_To_experimental_StorageSourceSpec(in *StorageSourceSpec, out *experimental.StorageSourceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_StorageSourceSpec_To_experimental_StorageSourceSpec(in, out, s)
}

func autoConvert_experimental_StorageSourceSpec_To_v1alpha1_StorageSourceSpec(in *experimental.StorageSourceSpec, out *StorageSourceSpec, s conversion.Scope) error {
	out.Bucket = in.Bucket
	out.Object = in.Object
	out.Generation = in.Generation
	return nil
}

// Convert_experimental_StorageSourceSpec_To_v1alpha1_StorageSourceSpec is an autogenerated conversion function.
func Convert_experimental_StorageSourceSpec_To_v1alpha1_StorageSourceSpec(in *experimental.StorageSourceSpec, out *StorageSourceSpec, s conversion.Scope) error {
	return autoConvert_experimental_StorageSourceSpec_To_v1alpha1_StorageSourceSpec(in, out, s)
}

func autoConvert_v1alpha1_VolumeSpec_To_experimental_VolumeSpec(in *VolumeSpec, out *experimental.VolumeSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_VolumeSpec_To_experimental_VolumeSpec is an autogenerated conversion function.
func Convert_v1alpha1_VolumeSpec_To_experimental_VolumeSpec(in *VolumeSpec, out *experimental.VolumeSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_VolumeSpec_To_experimental_VolumeSpec(in, out, s)
}

func autoConvert_experimental_VolumeSpec_To_v1alpha1_VolumeSpec(in *experimental.VolumeSpec, out *VolumeSpec, s conversion.Scope) error {
	out.Name = in.Name
	out.Path = in.Path
	return nil
}

// Convert_experimental_VolumeSpec_To_v1alpha1_VolumeSpec is an autogenerated conversion function.
func Convert_experimental_VolumeSpec_To_v1alpha1_VolumeSpec(in *experimental.VolumeSpec, out *VolumeSpec, s conversion.Scope) error {
	return autoConvert_experimental_VolumeSpec_To_v1alpha1_VolumeSpec(in, out, s)
}
